# Настройка работы ползунков микшера
# Впишите 'master' для управления общей системной громкостью
# Впишите название процесса для управления его громкостью
# Впишите 'mic' для управления громкостью микрофона
# Впишите 'deej.unmapped' для управления громкостью всех каналов, кроме используемых в ползунках
# Только Windows - Впишите 'deej.current' для управления громкостью приложения, которое сейчас в фокусе
# Только Windows - Вы можете вписать полное имя аудиоустройства, чтобы управлять его громкостью
# Только Windows - Вы можете вписать 'system' для управления громкостью звуков Windows, таких как уведомления
slider_mapping:
  0: master
  1: deej.current
  2: mic
  3: discord.exe
  4: chrome.exe

# Инвертирование значений ползунков микшера. (1023 - 0, 0 - 1023)
invert_sliders: false

# Настройки COM-порта. Впишите auto для автоопределения порта по USB PID/VID.
com_port: auto
baud_rate: 9600

# Настройки VID и PID для автоматического поиска COM-порта.
# Измените, если используете ваш микшер использует другой COM-конвертер.
# com_vid: 0x1A86
# com_pid: 0x7523

# Степень подавления шумов значений с микшера.
# Значения: low, default, high, none
# Используйте none, если подавление шумов происходит на стороне микшера.
noise_reduction: default

# Выбор языка. По умолчанию - auto, доступные варианты: ru, en, auto
language: auto
